'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { ThirdwebProvider, coinbaseWallet, localWallet, metamaskWallet, smartWallet } from "@thirdweb-dev/react";
import { Sepolia } from "@thirdweb-dev/chains";
import { SMARTWALLET_FACTORY_ADDRESS } from '@/utils/constants'

// TODO: Refactor/Cleanup here and NFTDisplay.tsx

const FACTORY_ADDRESS = SMARTWALLET_FACTORY_ADDRESS || '0x68d55de4Aa5554719A58A1d360d2c9b2EBD292bA';
const THIRDWEB_API_KEY = process.env.NEXT_PUBLIC_THIRDWEB_API_KEY as string;

const activeChain = Sepolia;

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebProvider
          activeChain={activeChain}
          supportedWallets={[
            smartWallet({
              factoryAddress: FACTORY_ADDRESS,
              thirdwebApiKey: THIRDWEB_API_KEY,
              gasless: true,
              personalWallets: [
                metamaskWallet(),
                coinbaseWallet(),
                localWallet({ persist: true }),
              ]
            }),
          ]}
        >
          {children}
        </ThirdwebProvider>
      </body>
    </html>
  )
}
